# Generated by Django 6.0.3 on 2026-03-27 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('text', models.TextField(help_text='The question text')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('NUMERICAL', 'Numerical'), ('CODE', 'Coding')], max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=4.0, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('individual_time_limit', models.PositiveIntegerField(blank=True, help_text='Seconds', null=True)),
                ('correct_numerical', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['serial_no'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='testing.question')),
            ],
        ),
        migrations.CreateModel(
            name='CodeTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testing.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('file_id', models.CharField(blank=True, max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='testing.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timer_type', models.CharField(choices=[('INDIVIDUAL', 'Per Question'), ('TOTAL', 'Total Test Time')], default='TOTAL', max_length=15)),
                ('total_duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='classroom.group')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.test'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, to='testing.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'serial_no')},
        ),
    ]
